# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab225c36bf38f6b44c25187556a3671ef86044b66edd51ebf233f1128773712b02021d048f8bb10086534a53f68325dd4c7e3674b351068e2e15e3dbadab31d2

test:
  secret_key_base: 91cf6dce8bc2f1ad5df1ca34dc3ee166f17711a9a007fdb3a4d7a9d93842834fbf9d9151557ed75e10867665568ce69df6e25015f3b36b26fbd9007fcb6a870e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
