source 'https://rubygems.org'


gem 'rails', '4.1.7'
gem 'pg'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
gem 'active_model_serializers', '0.8.3'
gem 'faker'
gem 'rails-api'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

